#!url=https://ybnet.ga/module/aliyun.module
#!name=zxy定时签到

#!desc=zxy定时签到

#!homepage=https://github.com/deezertidal

#!author=lowking

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/aliyun.png



[Script]

阿里云盘签到=type=cron,cronexp="0 10 0 * * ?",wake-system=1,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/ali/aliYunPanCheckIn.js

中国移动签到=type=cron,cronexp="0 10 0 * * ?",wake-system=1,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10086/10086.js






#cookie获取成功后请禁用

# 阿里云盘签到cookie=type=http-response,pattern=https:\/\/auth.aliyundrive.com\/v2\/account\/token,requires-body=1,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/ali/aliYunPanCheckIn.js

# 注意获取Cookie有两条脚本
# 中国移动签到cookie1=type=http-request,pattern=^http:\/\/wx.10086.cn\/website\/taskCenter\/index\?,requires-body=1,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10086/10086.cookie.js

# 中国移动签到cookie2=type=http-request,pattern=^http:\/\/wx.10086.cn\/website\/taskCenter\/sign\?,requires-body=1,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10086/10086.cookie.js




[MITM] 

hostname= %APPEND% auth.aliyundrive.com,wx.10086.cn
